version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    pre_build:
      commands:
        - echo "Moving to application directory."
        - cd online-delivery-system
        - echo "Installing dependencies."
        - mvn install -DskipTests=true
    build:
      commands:
        - echo "Building application."
        - mvn package -DskipTests=true
    post_build:
      commands:
        - echo "Build completed."
