SELECT * FROM users;
SELECT * FROM addresses;
SELECT * FROM payment_methods;
SELECT * FROM vendor;
SELECT * FROM delivery_person;
SELECT * FROM menu_items;
SELECT * FROM orders;
SELECT * FROM order_items;
SELECT * FROM transactions;
